#pragma once

#include <stdint.h>

/* Bitmap font generated by tools/fontgen.py (spec §4.4). */
typedef struct {
    uint32_t codepoint;
    uint32_t offset;  /* into gfx_font_t.bitmap */
    uint8_t width;    /* bitmap width in px */
    uint8_t height;   /* bitmap height in px */
    int8_t x_offset;  /* left edge relative to the pen */
    int8_t y_offset;  /* top edge relative to the baseline; negative is above */
    uint8_t advance;  /* pen advance in px */
} gfx_glyph_t;

typedef struct {
    const uint8_t *bitmap;     /* glyph rows, MSB first, each row padded to whole bytes, 1 = ink */
    const gfx_glyph_t *glyphs; /* sorted by codepoint */
    uint16_t glyph_count;
    uint8_t ascent;      /* baseline distance from the top of a line */
    uint8_t line_height; /* ascent + descent */
} gfx_font_t;
