#pragma once

#include "gfx.h"

/* Icons generated by tools/imggen.py from MaterialIcons-Regular.ttf (see THIRD_PARTY.md). */
extern const gfx_bitmap_t gfx_icon_thermometer_16;
extern const gfx_bitmap_t gfx_icon_thermometer_24;
extern const gfx_bitmap_t gfx_icon_thermometer_48;
extern const gfx_bitmap_t gfx_icon_drop_16;
extern const gfx_bitmap_t gfx_icon_drop_24;
extern const gfx_bitmap_t gfx_icon_drop_48;
extern const gfx_bitmap_t gfx_icon_dew_24;
extern const gfx_bitmap_t gfx_icon_dew_48;
extern const gfx_bitmap_t gfx_icon_bolt_16;
extern const gfx_bitmap_t gfx_icon_bolt_24;
extern const gfx_bitmap_t gfx_icon_stale_16;
extern const gfx_bitmap_t gfx_icon_stale_24;
extern const gfx_bitmap_t gfx_icon_clock_24;
extern const gfx_bitmap_t gfx_icon_clock_48;
extern const gfx_bitmap_t gfx_icon_calendar_24;
extern const gfx_bitmap_t gfx_icon_calendar_48;
extern const gfx_bitmap_t gfx_icon_person_24;
extern const gfx_bitmap_t gfx_icon_person_48;
extern const gfx_bitmap_t gfx_icon_celebration_24;
extern const gfx_bitmap_t gfx_icon_celebration_48;
extern const gfx_bitmap_t gfx_icon_cloud_24;
extern const gfx_bitmap_t gfx_icon_cloud_48;
