#!/usr/bin/env python3
"""Render a TrueType font into a 1-bpp bitmap font for components/gfx (spec §4.4).

Run it through tools/gen_fonts.sh, which supplies the pinned Pillow and fontTools via uv:
  uv run --python 3.13 --with-requirements tools/requirements.txt \
      tools/fontgen.py --ttf assets/fonts/DejaVuSans.ttf --size 16 --charset text --name sans_16
Writes components/gfx/fonts/gfx_font_<name>.c, which defines `const gfx_font_t gfx_font_<name>`.
Glyphs are rendered with FreeType's monochrome hinting, the mode Pillow uses for "1" images.
"""
import argparse
import pathlib
import sys

CHARSETS = {
    "ascii": [(0x20, 0x7E)],
    # ASCII, Latin-1, Latin Extended-A, dashes, ellipsis, euro, arrows
    "text": [(0x20, 0x7E), (0xA0, 0xFF), (0x100, 0x17F), (0x2013, 0x2014), (0x2026, 0x2026),
             (0x20AC, 0x20AC), (0x2190, 0x2193)],
    # large numerals: space % + , - . / 0-9 : ° minus
    "digits": [(0x20, 0x20), (0x25, 0x25), (0x2B, 0x3A), (0xB0, 0xB0), (0x2212, 0x2212)],
}


def parse_charset(spec):
    """'text' or 'ascii,0x20AC,0x2190-0x2193' -> sorted list of codepoints."""
    cps = set()
    for part in (p.strip() for p in spec.split(",")):
        if part in CHARSETS:
            for lo, hi in CHARSETS[part]:
                cps.update(range(lo, hi + 1))
        elif "-" in part:
            lo, hi = (int(v, 0) for v in part.split("-", 1))
            cps.update(range(lo, hi + 1))
        else:
            cps.add(int(part, 0))
    return sorted(cps)


def pack_rows(rows):
    """Rows of 0/1 pixels -> bytes, MSB first, each row padded to whole bytes."""
    out = bytearray()
    for row in rows:
        for start in range(0, len(row), 8):
            byte = 0
            for i, bit in enumerate(row[start:start + 8]):
                if bit:
                    byte |= 0x80 >> i
            out.append(byte)
    return bytes(out)


def render_glyph(font, cp):
    """One glyph as FreeType renders it in monochrome, positioned relative to the pen at the baseline."""
    from PIL import Image, ImageDraw

    ch = chr(cp)
    advance = round(font.getlength(ch, mode="1"))
    left, top, right, bottom = font.getbbox(ch, mode="1", anchor="ls")
    width, height = right - left, bottom - top
    if width <= 0 or height <= 0:
        return dict(cp=cp, width=0, height=0, x=0, y=0, advance=advance, rows=[])
    img = Image.new("1", (width, height), 0)
    draw = ImageDraw.Draw(img)
    draw.fontmode = "1"
    draw.text((-left, -top), ch, font=font, fill=1, anchor="ls")
    px = img.load()
    rows = [[1 if px[x, y] else 0 for x in range(width)] for y in range(height)]
    return dict(cp=cp, width=width, height=height, x=left, y=top, advance=advance, rows=rows)


def _check(glyph):
    ok = (0 <= glyph["width"] <= 255 and 0 <= glyph["height"] <= 255 and -128 <= glyph["x"] <= 127
          and -128 <= glyph["y"] <= 127 and 0 <= glyph["advance"] <= 255)
    if not ok:
        raise ValueError(f"glyph U+{glyph['cp']:04X} does not fit gfx_glyph_t: {glyph}")


def emit_c(name, source, size, glyphs, ascent, line_height):
    data = bytearray()
    offsets = []
    for glyph in glyphs:
        _check(glyph)
        offsets.append(len(data))
        data += pack_rows(glyph["rows"])
    lines = [
        f"/* Generated by tools/fontgen.py from {source} at {size} px. Do not edit; run tools/gen_fonts.sh. */",
        '#include "gfx_font.h"',
        "",
        "static const uint8_t s_bitmap[] = {",
    ]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    if not data:
        lines.append("    0x00,")
    lines += ["};", "", "static const gfx_glyph_t s_glyphs[] = {"]
    for glyph, offset in zip(glyphs, offsets):
        lines.append(f"    {{ 0x{glyph['cp']:04X}, {offset}, {glyph['width']}, {glyph['height']}, "
                     f"{glyph['x']}, {glyph['y']}, {glyph['advance']} }},")
    lines += [
        "};",
        "",
        f"const gfx_font_t gfx_font_{name} = {{ s_bitmap, s_glyphs, {len(glyphs)}, {ascent}, {line_height} }};",
        "",
    ]
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--ttf", required=True, help="TrueType/OpenType font file")
    parser.add_argument("--size", required=True, type=int, help="pixel size (em)")
    parser.add_argument("--charset", default="text", help="preset name and/or codepoints, comma separated")
    parser.add_argument("--name", required=True, help="C name suffix: gfx_font_<name>")
    parser.add_argument("--out", help="output .c (default: components/gfx/fonts/gfx_font_<name>.c)")
    args = parser.parse_args(argv)

    from fontTools.ttLib import TTFont
    from PIL import ImageFont

    cmap = TTFont(args.ttf).getBestCmap()
    font = ImageFont.truetype(args.ttf, args.size)
    ascent, descent = font.getmetrics()
    wanted = parse_charset(args.charset)
    glyphs = [render_glyph(font, cp) for cp in wanted if cp in cmap]
    missing = [f"U+{cp:04X}" for cp in wanted if cp not in cmap]
    out = pathlib.Path(args.out or f"components/gfx/fonts/gfx_font_{args.name}.c")
    out.write_text(emit_c(args.name, pathlib.Path(args.ttf).name, args.size, glyphs, ascent, ascent + descent),
                   encoding="utf-8")
    print(f"{out}: {len(glyphs)} glyphs, ascent {ascent}, line {ascent + descent}"
          + (f", not in font: {' '.join(missing)}" if missing else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
