#!/usr/bin/env python3
"""Writes web/zones.js: every IANA time zone of the tz database with its POSIX TZ string, for the
web UI's zone picker and "set time from phone" (spec §7, §10.3). The POSIX string is the last line
of each zone's TZif file (RFC 8536 §3.3); the tz database is in the public domain.

  python3 tools/gen_zones.py [--zoneinfo /usr/share/zoneinfo] [--out web/zones.js]
"""
import argparse
import json
import pathlib
import sys


def posix_of(path):
    """The footer of a TZif version 2+ file: the text between its last two newlines. None for a
    missing file, another format, a version 1 file (no footer) or an empty footer."""
    try:
        data = path.read_bytes()
    except OSError:
        return None
    if not data.startswith(b"TZif") or not data.endswith(b"\n"):
        return None
    start = data.rfind(b"\n", 0, len(data) - 1)
    try:
        footer = data[start + 1:-1].decode("ascii") if start >= 0 else ""
    except UnicodeDecodeError:
        return None
    return footer or None


def zones(zoneinfo):
    names = ["UTC"]
    for line in (zoneinfo / "zone.tab").read_text().splitlines():
        if line and not line.startswith("#"):
            names.append(line.split("\t")[2])
    table = {}
    for name in sorted(set(names)):
        posix = posix_of(zoneinfo / name)
        if posix:
            table[name] = posix
    return table


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--zoneinfo", default="/usr/share/zoneinfo")
    parser.add_argument("--out", default="web/zones.js")
    args = parser.parse_args(argv)
    zoneinfo = pathlib.Path(args.zoneinfo)
    version = (zoneinfo / "+VERSION").read_text().strip() if (zoneinfo / "+VERSION").exists() else "unknown"
    table = zones(zoneinfo)
    text = (f"// Generated by tools/gen_zones.py from tzdata {version}; do not edit.\n"
            f"// IANA zone -> POSIX TZ string (spec §7). The tz database is in the public domain.\n"
            f"const ZONES = {json.dumps(table, separators=(',', ':'), sort_keys=True)};\n")
    pathlib.Path(args.out).write_text(text)
    print(f"{args.out}: {len(table)} zones from tzdata {version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
