#!/usr/bin/env python3
"""Render icons from an icon font into 1-bpp C bitmaps for components/gfx (spec §4.5).

Run it through tools/gen_icons.sh, which supplies the pinned Pillow via uv:
  uv run --python 3.13 --with-requirements tools/requirements.txt tools/imggen.py \\
      --ttf assets/icons/MaterialIcons-Regular.ttf --codepoints assets/icons/MaterialIcons-Regular.codepoints \\
      --manifest assets/icons/icons.txt --licence assets/icons/LICENSE-MaterialIcons.txt
Writes components/gfx/icons/gfx_icons.c and components/gfx/include/gfx_icons.h. Each icon is a
square bitmap of its size (the font's em box), so icons of one size line up. Glyphs are rendered
with FreeType's monochrome hinting, like tools/fontgen.py.
"""
import argparse
import pathlib
import sys


def parse_manifest(text):
    """'c_name source_name size...' lines -> [(c_name, source_name, [sizes])]; '#' starts a comment."""
    icons = []
    for number, line in enumerate(text.splitlines(), 1):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 3 or not parts[0].isidentifier():
            raise ValueError(f"manifest line {number}: expected 'c_name source_name size...': {line!r}")
        icons.append((parts[0], parts[1], [int(s) for s in parts[2:]]))
    return icons


def parse_codepoints(text):
    """Material Icons' 'name hex' lines -> {name: codepoint}."""
    return {name: int(hexcp, 16) for name, hexcp in (line.split() for line in text.splitlines() if line.strip())}


def pack_rows(rows):
    """Rows of 0/1 pixels -> bytes, MSB first, each row padded to whole bytes."""
    out = bytearray()
    for row in rows:
        for start in range(0, len(row), 8):
            byte = 0
            for i, bit in enumerate(row[start:start + 8]):
                if bit:
                    byte |= 0x80 >> i
            out.append(byte)
    return bytes(out)


def render_icon(font, codepoint, size):
    """size x size rows of 0/1, the glyph drawn at the em box's top-left corner."""
    from PIL import Image, ImageDraw

    img = Image.new("1", (size, size), 0)
    draw = ImageDraw.Draw(img)
    draw.fontmode = "1"
    draw.text((0, 0), chr(codepoint), font=font, fill=1)
    px = img.load()
    return [[1 if px[x, y] else 0 for x in range(size)] for y in range(size)]


def emit_c(icons, source, licence=None):
    """icons: [(symbol, size, rows)] -> the .c file text."""
    lines = [
        f"/* Generated by tools/imggen.py from {source}. Do not edit; run tools/gen_icons.sh. */",
        *([f"/* Icon licence: {licence} (it also covers these bitmaps). */"] if licence else []),
        '#include "gfx_icons.h"',
        "",
    ]
    for symbol, size, rows in icons:
        data = pack_rows(rows)
        lines.append(f"static const uint8_t s_{symbol}[] = {{")
        for i in range(0, len(data), 16):
            lines.append("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
        lines += ["};", f"const gfx_bitmap_t gfx_icon_{symbol} = {{ s_{symbol}, {size}, {size} }};", ""]
    return "\n".join(lines)


def emit_h(icons, source):
    lines = [
        "#pragma once",
        "",
        '#include "gfx.h"',
        "",
        f"/* Icons generated by tools/imggen.py from {source} (see THIRD_PARTY.md). */",
    ]
    lines += [f"extern const gfx_bitmap_t gfx_icon_{symbol};" for symbol, _size, _rows in icons]
    return "\n".join(lines) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--ttf", required=True, help="icon font")
    parser.add_argument("--codepoints", required=True, help="the font's 'name hex' codepoint list")
    parser.add_argument("--manifest", required=True, help="icons to render: 'c_name source_name size...'")
    parser.add_argument("--licence", help="licence file of the icons, named in the generated source")
    parser.add_argument("--out-c", default="components/gfx/icons/gfx_icons.c")
    parser.add_argument("--out-h", default="components/gfx/include/gfx_icons.h")
    args = parser.parse_args(argv)

    from PIL import ImageFont

    codepoints = parse_codepoints(pathlib.Path(args.codepoints).read_text())
    rendered = []
    for c_name, source_name, sizes in parse_manifest(pathlib.Path(args.manifest).read_text()):
        if source_name not in codepoints:
            raise SystemExit(f"{source_name}: not in {args.codepoints}")
        for size in sizes:
            font = ImageFont.truetype(args.ttf, size, layout_engine=ImageFont.Layout.BASIC)
            rendered.append((f"{c_name}_{size}", size, render_icon(font, codepoints[source_name], size)))
    source = pathlib.Path(args.ttf).name
    pathlib.Path(args.out_c).write_text(emit_c(rendered, source, args.licence), encoding="utf-8")
    pathlib.Path(args.out_h).write_text(emit_h(rendered, source), encoding="utf-8")
    print(f"{args.out_c}: {len(rendered)} icons")
    return 0


if __name__ == "__main__":
    sys.exit(main())
